Vagrant.configure(2) do |config|
    config.vm.box = "generic/debian12"
    config.vm.synced_folder ".", "/vagrant", type: "rsync"
    config.vm.provider :libvirt do |v|
        v.default_prefix = "" 
        v.random_hostname = false

        v.memory = 2048
        v.cpus = 2
    end

    # Machine for dev tests, delete before eval
    config.vm.define "ipetrovS" do |control|
        control.vm.hostname = "ipetrovS"
        control.vm.network :private_network, ip: "192.168.56.110", libvirt__dhcp_enabled: false
        control.vm.provision "shell", inline: <<-SHELL
            export DEBIAN_FRONTEND=noninteractive
            apt-get update -qq
            cd /vagrant/scripts/
            ./init-cluster.sh
            ./init-argocd.sh
        SHELL
    end
end
